FROM python:3.10
USER root
WORKDIR /app
COPY .. /app/
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


RUN python3 /app/model.py
CMD ["streamlit", "run", "app_OCT.py","--server.port=8501", "server.address=0.0.0.0"]

